"""Single source of truth for backend configuration and shared literals."""

from __future__ import annotations

import os
from pathlib import Path


# Environment variables
ENV_VOICEBOX_PORT = "VOICEBOX_PORT"
ENV_PROXY_PORT = "PROXY_PORT"
ENV_VOICEBOX_DATA_DIR = "VOICEBOX_DATA_DIR"
ENV_HF_HOME = "HF_HOME"
ENV_BACKEND_PORT = "BACKEND_PORT"
ENV_BACKEND_HOST = "BACKEND_HOST"
ENV_AUTO_RESTART_MINUTES = "AUTO_RESTART_MINUTES"
ENV_PRELOAD_MODELS = "PRELOAD_MODELS"
ENV_SERVERLESS = "SERVERLESS"
ENV_HSA_OVERRIDE_GFX_VERSION = "HSA_OVERRIDE_GFX_VERSION"
ENV_MIOPEN_LOG_LEVEL = "MIOPEN_LOG_LEVEL"
ENV_HF_TOKEN = "HF_TOKEN"
ENV_HUGGING_FACE_HUB_TOKEN = "HUGGING_FACE_HUB_TOKEN"


# Network defaults
LOCALHOST = "127.0.0.1"
WILDCARD_HOST = "0.0.0.0"
BACKEND_HOST = LOCALHOST
VOICEBOX_PORT_DEFAULT = 17493
PROXY_PORT_DEFAULT = 17494
API_BIND_PORT_DEFAULT = 8000
HEALTH_PATH = "/health"
SHUTDOWN_PATH = "/shutdown"
AUTH_ME_PATH = "/auth/me"
PROFILES_PATH = "/profiles"
PROFILES_IMPORT_PATH = "/profiles/import"
GENERATE_STREAM_PATH = "/generate?stream=true"
GENERATE_PROGRESS_PATH_TEMPLATE = "/generate/progress/{generation_id}"
HISTORY_PATH = "/history"
AUDIO_PATH_TEMPLATE = "/audio/{generation_id}"
PROXY_STATUS_PATH = "/_proxy/status"
PROXY_START_PATH = "/_proxy/start"
PROXY_STOP_PATH = "/_proxy/stop"
PROXY_RESTART_PATH = "/_proxy/restart"


def build_base_url(host: str, port: int) -> str:
    return f"http://{host}:{port}"


# Filesystem defaults
VOICEBOX_DATA_DIR_DEFAULT = "/runpod-volume/voicebox"
HF_HOME_DEFAULT = "/runpod-volume/huggingface-cache"
HF_HOME_SUBDIR = "huggingface"
DATABASE_FILENAME = "voicebox.db"
MODEL_PREFS_FILENAME = "model_prefs.json"
PROFILES_SUBDIR = "profiles"
GENERATIONS_SUBDIR = "generations"
CACHE_SUBDIR = "cache"
MODELS_SUBDIR = "models"
APP_LOG_PATH = "/app/app.log"
CLI_DEFAULT_DATA_DIR = Path.home() / "Library/Application Support/sh.voicebox.app"
CLI_SERVER_BIN = "/Applications/Voicebox.app/Contents/MacOS/voicebox-server"
CLI_PID_FILENAME = ".voicebox.pid"
CLI_LOG_FILENAME = ".voicebox.log"


# Common API / model defaults
DEFAULT_LANGUAGE = "en"
SUPPORTED_LANGUAGES = ("zh", "en", "ja", "ko", "de", "fr", "ru", "pt", "es", "it")
SUPPORTED_LANGUAGES_PATTERN = "^(" + "|".join(SUPPORTED_LANGUAGES) + ")$"
MAX_PROFILE_NAME_LENGTH = 100
MAX_PROFILE_DESCRIPTION_LENGTH = 500
MAX_SAMPLE_REFERENCE_TEXT_LENGTH = 1000
MAX_GENERATION_TEXT_LENGTH = 5000
MAX_INSTRUCT_LENGTH = 500
MAX_REQUEST_USER_ID_LENGTH = 128
MAX_REQUEST_USER_FIRST_NAME_LENGTH = 64
DEFAULT_HISTORY_LIMIT = 20
MAX_HISTORY_LIMIT = 100


# Queue / job status constants
JOB_STATUS_QUEUED = "queued"
JOB_STATUS_GENERATING = "generating"
JOB_STATUS_CANCELLING = "cancelling"
JOB_STATUS_COMPLETE = "complete"
JOB_STATUS_CANCELLED = "cancelled"
JOB_STATUS_ERROR = "error"
JOB_STATUS_TIMEOUT = "timeout"
JOB_STATUS_DELETED = "deleted"
JOB_ACTIVE_STATUSES = (
    JOB_STATUS_QUEUED,
    JOB_STATUS_GENERATING,
    JOB_STATUS_CANCELLING,
)
JOB_RUNNING_STATUSES = (
    JOB_STATUS_GENERATING,
    JOB_STATUS_CANCELLING,
)
DEFAULT_JOB_STATUS_FILTER = ",".join(
    (
        JOB_STATUS_QUEUED,
        JOB_STATUS_GENERATING,
        JOB_STATUS_CANCELLING,
        JOB_STATUS_COMPLETE,
    )
)
HEALTHY_STATUS = "healthy"
JOB_STATUS_LOADING = "loading"
QUEUE_TIMEOUT_MESSAGE = "Queue timeout"
GENERATION_TIMEOUT_MESSAGE = "Generation timeout"
CANCELLED_BY_USER_MESSAGE = "Cancelled by user"
FORCE_CANCELLED_BY_USER_MESSAGE = "Force-cancelled by user"
AUTH_UNAVAILABLE_MESSAGE = "Authentication not available"
SHUTTING_DOWN_MESSAGE = "Shutting down..."
UNKNOWN_IP = "unknown"


# Runtime / timing defaults
MAX_ACTIVE_JOBS_PER_USER = 3
QUEUED_JOB_TIMEOUT_MINUTES = 15
GENERATING_JOB_TIMEOUT_MINUTES = 5
AUTO_RESTART_MINUTES_DEFAULT = 0
HEALTH_RESPONSE_DELAY_SECONDS = 0.1
JOB_WORKER_POLL_SECONDS = 2.0
PROXY_STOP_TIMEOUT_SECONDS = 10
PROXY_RESTART_DELAY_SECONDS = 0.5
PROXY_REQUEST_TIMEOUT_SECONDS = 300
SERVERLESS_STARTUP_TIMEOUT_SECONDS = 300
SERVERLESS_STARTUP_POLL_SECONDS = 2
SERVERLESS_HEALTHCHECK_TIMEOUT_SECONDS = 5
SERVERLESS_REQUEST_TIMEOUT_SECONDS = 600
CLI_API_TIMEOUT_SECONDS = 30
CLI_HEALTHCHECK_TIMEOUT_SECONDS = 2
CLI_STREAM_START_TIMEOUT_SECONDS = 10
CLI_STREAM_PROGRESS_TIMEOUT_SECONDS = 300
CLI_FILE_TRANSFER_TIMEOUT_SECONDS = 60
CLI_SERVER_READY_WAIT_SECONDS = 30
CLI_SERVER_READY_POLL_SECONDS = 0.5
CLI_SERVER_READY_POLL_COUNT = int(CLI_SERVER_READY_WAIT_SECONDS / CLI_SERVER_READY_POLL_SECONDS)
HF_MASKED_TOKEN_PREFIX_LENGTH = 4
LATEST_HISTORY_RESULT_LIMIT = 1
SERVERLESS_HTTP_METHOD_DEFAULT = "POST"
SERVERLESS_JSON_METHODS = ("POST", "PUT", "PATCH")
SERVERLESS_BINARY_CONTENT_TYPES = (
    "audio/",
    "application/octet-stream",
    "application/zip",
)
SERVERLESS_MISSING_PATH_MESSAGE = "Missing 'path' in job input"


# Headers / middleware
HEADER_X_FORWARDED_FOR = "x-forwarded-for"
HEADER_X_REAL_IP = "x-real-ip"
HEADER_CONTENT_LENGTH = "Content-Length"
HEADER_TRANSFER_ENCODING = "transfer-encoding"
HEALTH_HEADER_MODEL_LOADED = "X-Health-Model-Loaded"
HEALTH_HEADER_MODEL_SIZE = "X-Health-Model-Size"
HEALTH_HEADER_GPU_TYPE = "X-Health-GPU-Type"
HEALTH_HEADER_BACKEND = "X-Health-Backend"
HEALTH_EXPOSED_HEADERS = [
    HEALTH_HEADER_MODEL_LOADED,
    HEALTH_HEADER_MODEL_SIZE,
    HEALTH_HEADER_GPU_TYPE,
    HEALTH_HEADER_BACKEND,
]
SSE_CACHE_CONTROL = "no-cache"
SSE_CONNECTION = "keep-alive"
SSE_ACCEL_BUFFERING_DISABLED = "no"


# GPU/runtime environment defaults
HSA_OVERRIDE_GFX_VERSION_DEFAULT = "10.3.0"
MIOPEN_LOG_LEVEL_DEFAULT = "4"


_DEFAULTS = {
    ENV_VOICEBOX_PORT: str(VOICEBOX_PORT_DEFAULT),
    ENV_PROXY_PORT: str(PROXY_PORT_DEFAULT),
    ENV_VOICEBOX_DATA_DIR: VOICEBOX_DATA_DIR_DEFAULT,
}

_conf = {key: os.environ.get(key, default) for key, default in _DEFAULTS.items()}
_conf[ENV_HF_HOME] = os.environ.get(
    ENV_HF_HOME,
    HF_HOME_DEFAULT,
)

VOICEBOX_PORT = int(_conf[ENV_VOICEBOX_PORT])
PROXY_PORT = int(_conf[ENV_PROXY_PORT])
DATA_DIR = _conf[ENV_VOICEBOX_DATA_DIR]
HF_HOME = _conf[ENV_HF_HOME]
